FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openssh-server software-properties-common
RUN apt-add-repository ppa:ansible/ansible && apt update && apt install -y ansible
RUN apt-get clean autoclean && apt-get autoremove --yes
RUN rm -rf /var/lib/{apt,dpkg,cache,log}/
RUN mkdir /var/run/sshd
RUN echo 'root:P@ssw0rd123' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
WORKDIR /home/ansible
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
